Centos6:
  image: "centos:6"
  before_script:
    - rpm -i https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm
    - yum -y install ansible openssh-server openssh-client git
    - useradd -m tmolnar
    - service sshd start
  script:
    - ansible-playbook --syntax-check -i tests/inventory tests/test.yml
    - ansible-playbook -i tests/inventory tests/test.yml --connection=local -u root --become-user=root
    - ansible-playbook -i tests/inventory tests/test.yml --connection=local -u root --become-user=root | grep 'changed=0.*failed=0' || exit 1
    - which vim || exit 1
    - which tmux || exit 1
    - which mc || exit 1
    
Centos7:
  image: "centos:7"
  before_script:
    - rpm -i https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    - yum -y install ansible openssh-server git
    - useradd -m tmolnar
  script:
    - ansible-playbook --syntax-check -i tests/inventory tests/test.yml
    - ansible-playbook -i tests/inventory tests/test.yml --connection=local -u root --become-user=root
    - ansible-playbook -i tests/inventory tests/test.yml --connection=local -u root --become-user=root | grep 'changed=0.*failed=0' || exit 1
    - which vim || exit 1
    - which tmux || exit 1
    - which mc || exit 1
    
Ubuntu14:
  image: "ubuntu:14.04"
  before_script:
    - apt-get update && apt-get -y install software-properties-common openssh-server git
    - apt-add-repository ppa:ansible/ansible && apt-get update && apt-get -y install ansible
    - useradd -m tmolnar
  script:
    - ansible-playbook --syntax-check -i tests/inventory tests/test.yml
    - ansible-playbook -i tests/inventory tests/test.yml --connection=local -u root --become-user=root
    - ansible-playbook -i tests/inventory tests/test.yml --connection=local -u root --become-user=root | grep 'changed=0.*failed=0' || exit 1
    - which vim || exit 1
    - which tmux || exit 1
    - which mc || exit 1
    
Ubuntu16:
  image: "ubuntu:16.04"
  before_script:
    - apt-get update && apt-get -y install ansible openssh-server git
    - useradd -m tmolnar
  script:
    - ansible-playbook --syntax-check -i tests/inventory tests/test.yml
    - ansible-playbook -i tests/inventory tests/test.yml --connection=local -u root --become-user=root
    - ansible-playbook -i tests/inventory tests/test.yml --connection=local -u root --become-user=root | grep 'changed=0.*failed=0' || exit 1
    - which vim || exit 1
    - which tmux || exit 1
    - which mc || exit 1
