---
- name: Set up the user accounts
  user:
    name: "{{ item.name }}"
    shell: "{{ item.shell|default('/bin/bash') }}"
    home: "{{ item.home }}"
  with_items: "{{ users }}"
  tags:
    - users
      
- name: Set up the user password 
  user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
  with_items: "{{ users_private }}"
  no_log: yes
  tags:
    - users

- name: Create the .ssh directory
  file:
    state: directory
    dest: "{{ item.home }}/.ssh"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0700
  with_items: "{{ users }}"
  tags:
    - users

- name: Deploy the private key files
  copy:
    content: "{{ item.1.content }}"
    dest: "{{ item.1.file }}"
    owner: "{{ item.0.name }}"
    group: "{{ item.0.name }}"
    mode: 0400
  with_subelements:
    - "{{ users_private }}"
    - private_keys
    - skip_missing: yes
  no_log: yes
  tags:
    - users

- name: Deploy the public key files
  copy:
    content: "{{ item.1.content }}"
    dest: "{{ item.1.file }}"
    owner: "{{ item.0.name }}"
    group: "{{ item.0.name }}"
    mode: 0400
  with_subelements:
    - "{{ users }}"
    - public_keys
    - skip_missing: yes 
  tags:
    - users

- name: Deploy the authorized_key
  authorized_key:
    user: "{{ item.0.name }}"
    key: "{{ item.1 }}"
    state: present
  with_subelements:
    - "{{ users }}"
    - authorized
    - skip_missing: yes
  tags:
    - users
  when: item.1 is defined
