---
- name: Set up the user accounts
  user:
    name: "{{ item.name }}"
    shell: "{{ item.shell|default('/bin/bash') }}"
    password: "{{ item.password }}"
    home: "{{ item.home }}"
  with_items: "{{ users }}"
  tags:
    - users

- name: Create the .ssh directory
  file:
    state: directory
    dest: "{{ item.home }}/.ssh"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0700
  with_items: "{{ users }}"
  tags:
    - users

- name: Deploy the private key files
  copy:
    content: "{{ item.1.content }}"
    dest: "{{ item.1.file }}"
    owner: "{{ item.0.name }}"
    group: "{{ item.0.name }}"
    mode: 0400
  with_subelements:
    - "{{ users }}"
    - private_keys
    - skip_missing: yes 
  tags:
    - users

- name: Deploy the public key files
  copy:
    content: "{{ item.1.content }}"
    dest: "{{ item.1.file }}"
    owner: "{{ item.0.name }}"
    group: "{{ item.0.name }}"
    mode: 0400
  with_subelements:
    - "{{ users }}"
    - public_keys
    - skip_missing: yes 
  tags:
    - users

- name: Deploy the authorized_key
  authorized_key:
    user: "{{ item.0.name }}"
    key: "{{ item.1 }}"
    state: present
  with_subelements:
    - "{{ users }}"
    - authorized
    - skip_missing: yes
  tags:
    - users
  when: item.1 is defined

- name: Configure the .emacs
  copy:
    src: emacs
    dest: "{{ item.home }}/.emacs"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0644
  with_items: "{{ users }}"
  tags:
    - users
    - emacs_config
  when: item.manage_emacs is defined

- name: Configure the .bashrc
  blockinfile:
    dest: "{{ item.home }}/.bashrc"
    block: "{{ item.bashrc_lines|default('') }}"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    state: present
  with_items: "{{ users }}"
  tags:
    - users
    - bash_config

- name: Configure the .vimrc
  copy:
    src: vimrc
    dest: "{{ item.home }}/.vimrc"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0644
  with_items: "{{ users }}"
  when: item.manage_vimrc is defined 
  tags:
    - users
    - vim_config

- name: Configure the .tmux.conf
  copy:
    src: "tmux.conf"
    dest: "{{ item.home }}/.tmux.conf"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0644
  with_items: "{{ users }}"
  when: item.manage_tmuxconf is defined 
  tags:
    - users
    - tmux_config

