---
- name: Set up the user accounts
  user:
    name: "{{ item.name }}"
    shell: "{{ item.shell|default('/bin/bash') }}"
    password: "{{ item.password }}"
    home: "{{ item.home }}"
  with_items: "{{ users }}"
  tags:
    - users

- name: Deploy the authorized_keys
  authorized_key:
    key: "{{ item.ssh_public_key }}"
    user: "{{ item.name }}"
    state: present
    exclusive: yes
  with_items: "{{ users }}"
  tags:
    - users
  when: item.ssh_key is defined

- name: Configure the .bashrc
  blockinfile:
    dest: "{{ item.home }}/.bashrc"
    block: "{{ item.bashrc_lines|default('') }}"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    state: present
  with_items: "{{ users }}"
  tags:
    - users

- name: Configure the .vimrc
  copy:
    src: vimrc
    dest: "{{ item.home }}/.vimrc"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0644
  with_items: "{{ users }}"
  when: item.manage_vimrc is defined 
  tags:
    - users
    - vim_config

- name: Configure the .tmux.conf
  copy:
    src: "tmux.conf"
    dest: "{{ item.home }}/.tmux.conf"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0644
  with_items: "{{ users }}"
  when: item.manage_tmuxconf is defined 
  tags:
    - users
    - tmux_config

